<?php
/**
 * Implements hook_chart_definition_alter().
 */
function YOURMODULE_chart_definition_alter(&$definition, $chart, $chart_id) {
  if(!empty($chart['#raw_options'])){
    $definition = _drupal_array_merge_deep_array(array($definition, $chart['#raw_options']));
  }
}

/**
 * Override drupal_array_merge_deep_array
 *
 * @param $arrays
 *
 * @return array
 */
function _drupal_array_merge_deep_array($arrays) {
  $result = array();

  foreach ($arrays as $array) {
    foreach ($array as $key => $value) {
      // Renumber integer keys as array_merge_recursive() does. Note that PHP
      // automatically converts array keys that are integer strings (e.g., '1')
      // to integers.
      if (isset($result[$key]) && is_array($result[$key]) && is_array($value)) {
        $result[$key] = _drupal_array_merge_deep_array(array($result[$key], $value));
      }
      // Otherwise, use the latter value, overriding any previous value.
      else {
        $result[$key] = $value;
      }
    }
  }

  return $result;
}
?> 
